default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: Hibot_development

test:
  <<: *default
  database: Hibot_test

production:
  <<: *default
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: Hibot_production